### PR TITLE
Create include.xml

### PR DESCRIPTION
**Pull request by jgranick**
I've integrated an initial go of hxtelemetry support in OpenFL :smile:

https://github.com/openfl/openfl/commit/1601be4518a9151162cc1989e82c0fcfa1b8ce2b

If the user defines "telemetry" or "advanced-telemetry" it should include the hxtelemetry haxelib when targeting C++ targets.

``` bash
openfl test windows -Dtelemetry
```

In order to make hxtelemetry work on C++, I understand you need an additional two defines when compiling. This pull should allow these to be added automatically when a user has the hxtelemetry library included with an OpenFL project

### CODE REVIEW

**Comment by ruby0x1** [comment]
Please can we avoid framework specific details in what is supposed to be heading toward a hxcpp specific library :)

**Comment by jcward** [comment]
@underscorediscovery - indeed, this changeset is framework agnostic, and the OpenFL changeset is complementary (basically a merge from my OpenFL fork.). Rest assured, nothing in hxtelemetry is OpenFL-specific. =)

@jgranick - cool, thanks for taking the initiative to get this integrated! I'll accept this request and push up my hxtelemetry library to haxelib. I think there's a dummy placeholder there for now.

Certainly the OpenFL telemetry integration I prototyped is more beta and likely to change than the hxcpp / hxtelemetry stuff. All I've done is measure event handlers and the render function (or at least, what I think is the event handlers and render function) from Stage.hx (as you likely saw.) It's built so that frameworks can define various things users will likely want to measure, while also allowing the user code to define and measure custom metrics as well. We'll probably want to add things like draw calls, GPU memory usage, etc.

My plan was to make the [sendMetric and sendSpanMetric](https://github.com/openfl/openfl/commit/1601be4518a9151162cc1989e82c0fcfa1b8ce2b#diff-fc3d29440d69d72a111b4d04c89c6b95R29) in OpenFL's Telemetry.hx use either hxtelemetry (for ccp) or fall through to the [Flash Telemetry API](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/profiler/Telemetry.html) (as requested by @delahee). Seems like a nice setup.

**Comment by jcward** [comment]
@jgranick - I'm trying to update hxtelemetry to use the latest OpenFL, but then I need the latest lime, and I'm having a hard time building lime legacy.  Any ideas:

```
>lime rebuild linux -Dlegacy
Error: Could not find include file "lib/cairo/files.xml"
```

lime/project/lib/cairo is empty

**Comment by jcward** [comment]
@jgranick - Forget lime build, not the top priority.

Also, I'm getting:

```
/home/jward/dev/openfl/openfl/profiler/Telemetry.hx:74: characters 20-35 : Class<openfl._legacy.Lib> has no field application
```

I like how you're [setting the app title](https://github.com/openfl/openfl/commit/1601be4518a9151162cc1989e82c0fcfa1b8ce2b#diff-fc3d29440d69d72a111b4d04c89c6b95R68), though it seems not available in legacy? However, users will still need some way to set `config.host` and `config.port` (and other variables in the config). My [static configuration](https://github.com/jcward/hxtelemetry/blob/master/test/DisplayingABitmap/Source/Main.hx#L18-L30) was a little weird but it worked. It would need [public static accessors](https://github.com/jcward/openfl/blob/hxt_prototyping/openfl/Telemetry.hx#L32-L37) in Telemetry.hx. Unless this is typically done a better way. I don't like Flash's `.telemetry.cfg` file mechanism, and it seems like too much data to put in compiler defines (would also cause unnecessary recompiles.)

**Comment by jcward** [comment]
@jgranick - ~~Oh, one more compiler error:~~

```
/home/jward/dev/openfl/openfl/profiler/Telemetry.hx:72: characters 15-40 : Class not found : HxTelemetry
```

~~Why is HxTelemetry class not found? I assume it has to do with my file/directory structure? One class per file? I had it working by always inlining `hxtelemetry.HxTelemetry`, but shouldn't the [import statement](https://github.com/openfl/openfl/commit/1601be4518a9151162cc1989e82c0fcfa1b8ce2b#diff-fc3d29440d69d72a111b4d04c89c6b95R5) take care of that? Why is Haxe so darn squirrelly?~~

Ah, crimmeny, it's that Module/package/class confusing error message again. [This line](https://github.com/openfl/openfl/commit/1601be4518a9151162cc1989e82c0fcfa1b8ce2b#diff-fc3d29440d69d72a111b4d04c89c6b95R71) needs lowercase hxtelemetry (package name):

```
    var config = new hxtelemetry.Config ();
```

**Comment by ruby0x1** [comment]
fwiw, include.xml is specific to openfl build toolchain. This change is not agnostic to anything.

**Comment by jcward** [comment]
@underscorediscovery - ah, I didn't know that, I assumed it was a haxelib thing.

**Comment by jcward** [comment]
I think ideally the file would be named accordingly -- something like `openfl-include.xml` but that's clearly a much larger and more ingrained issue.

It's tricky - if OpenFL knows about telemetry and hxtelemetry, you could argue that it might as well know that telemetry requires `HXCPP_TELEMETRY` and `HXCPP_STACK_TRACE`. Then again, those conditionals are hxcpp concerns, and hxtelemetry is a fairly small lib that sits between those (or somewhat to the side), and one could argue that they aren't OpenFL's concern. If they change, it'd be best to only change hxtelemetry and not OpenFL.

hxtelemetry will have inter-op implications with hxcpp, hxscout, and frameworks. It'll be very difficult to avoid any and all cross-project couplings. So unless there's a more standard way of expressing compiler conditions, a small, additive file for OpenFL seems fairly unobtrusive to me.

**Pull request merged**
